name: basic
on:
  push:
    branches: ['master']
jobs:
  check:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    name: Check hello-world-dep.agda
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4.3'
          agda-stdlib-version: '2.0'

      # Check hello-world-dep.agda, which you can find in tests/agda-stdlib:
      - run: |
          agda --compile-dir=build/ -c test.agda
        working-directory: .

      - run: ./build/test
        working-directory: .